spring.application.name=ASTU_JMEE-JLEE
server.port=8082

#local server
spring.datasource.url=jdbc:mysql://localhost:3306/jmee_jlee
spring.datasource.username=root
spring.datasource.password=saurabh1412
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#spring.datasource.url=jdbc:mysql://43.205.13.87:3306/ssuhs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=yuvi@7291

#debug=true
#logging.level.root=INFO

