# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Confirm JAR creation
      run: echo "JAR file created successfullsy"

    - name: List target directory
      run: ls -lh target

    - name: Copy JAR to EC2 (/home/ubuntu/AgriPGProjectUAT)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "target/ASTU_JMEE-JLEE-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/ASTU_CEE_JMEE_UAT/"

    - name: Confirm JAR Copy to EC2 Server
      run: echo "JAR file Copied successfully"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/AgriPGProjectUAT

          echo "🛑 Stopping & removing old container...."
          docker rm -f astuceejmee-container

          echo "🧹 Removing old image..."
          docker rmi astuceejmee-app

          echo "📦 Building new Docker image..."
          docker build -t astuceejmee-app .


          echo "🚀 Running container..."
          docker run -d --name astuceejmee-container -p 8081:8081 astuceejmee-app

          echo "✅ Deployment completed! "
